version: '3.7'

services:
  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DATABASE: StonePagamentosAPI

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.2.3-bionic
    restart: always
    ports:
      - "27017:27017"